# OCR

### Create a dataframe with bounding boxes for a receipt.

In [1]:
import cv2 
import pytesseract
from pytesseract import Output
import numpy as np
import pandas as pd 

pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

In [2]:
# Image path (input & output)
image = r'C:\Users\Tan Jia Xin\Documents\Aimazing\GCN\info_extraction_receipts\data\raw\img\000.jpg'
output = r'C:\Users\Tan Jia Xin\Documents\AImazing\GCN\img\tess_000.jpg'

# Using cv2.imread() method
# cv2.imread() method loads an image from the specified file. If the image cannot be read, it returns an empty matrix.
img = cv2.imread(image)

# Displaying the image
# cv2.imshow('image', img)

# Displaying the matrix
img

array([[[247, 252, 253],
        [247, 252, 253],
        [247, 252, 253],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[248, 253, 254],
        [248, 253, 254],
        [248, 253, 254],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[250, 255, 255],
        [250, 255, 255],
        [250, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[192, 202, 209],
        [198, 208, 215],
        [211, 221, 228],
        ...,
        [232, 235, 243],
        [222, 225, 233],
        [214, 217, 225]],

       [[196, 206, 213],
        [202, 212, 219],
        [211, 221, 228],
        ...,
        [215, 218, 226],
        [202, 205, 213],
        [192, 195, 203]],

       [[202, 212, 219],
        [206, 216, 223],
        [212, 222, 229],
        ...,
        [197, 200, 208],
        [185, 188, 196],
        [175, 178, 186]]], dtype=uint8)

image_to_string Returns unmodified output as string from Tesseract OCR processing  
image_to_boxes Returns result containing recognized characters and their box boundaries  
image_to_data Returns result containing box boundaries, confidences, and other information. Requires Tesseract 3.05+. For more information, please check the Tesseract TSV documentation

In [3]:
# Additional custom configuration
# page segmentation mode (psm) 6 = Assume a single uniform block of text.
# OCR engine mode (oem) 3 = Default, based on what is available (legacy or LSTM).
custom_config = r'--oem 3 --psm 6'

# Using this dictionary, we can get each word detected, their bounding box information, the text in them and the 
# confidence scores for each (conf) and store the output in dict.
d = pytesseract.image_to_data(img, output_type=Output.DICT) #, config=custom_config)
print(d.keys())
d

# Print out d (all key value pairs in d) in a table
pd.set_option('display.max_rows', 500)
d_table = pytesseract.image_to_data(img, output_type='data.frame')
d_table

dict_keys(['level', 'page_num', 'block_num', 'par_num', 'line_num', 'word_num', 'left', 'top', 'width', 'height', 'conf', 'text'])

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
0,1,1,0,0,0,0,0,0,463,1013,-1.000000,NaN
1,2,1,1,0,0,0,75,32,244,31,-1.000000,NaN
2,3,1,1,1,0,0,75,32,244,31,-1.000000,NaN
3,4,1,1,1,1,0,75,32,244,31,-1.000000,NaN
4,5,1,1,1,1,1,75,32,51,23,92.892517,tan
5,5,1,1,1,1,2,138,37,91,18,92.174042,woon
6,5,1,1,1,1,3,241,37,78,26,92.543823,yann
7,2,1,2,0,0,0,73,95,346,136,-1.000000,NaN
8,3,1,2,1,0,0,73,95,346,136,-1.000000,NaN
9,4,1,2,1,1,0,73,95,346,17,-1.000000,NaN
10,5,1,2,1,1,1,73,97,52,13,95.954277,BOOK
11,5,1,2,1,1,2,132,97,46,13,4.496620,TAK
12,5,1,2,1,1,3,186,95,75,17,92.446991,(TAMAN
13,5,1,2,1,1,4,269,95,58,17,92.669708,DAYA)
14,5,1,2,1,1,5,338,96,32,13,96.444664,SDN
15,5,1,2,1,1,6,380,96,39,13,50.636715,BHD
16,4,1,2,1,2,0,209,122,76,14,-1.000000,NaN
17,5,1,2,1,2,1,209,122,76,14,0.000000,PBO4N7-W
18,4,1,2,1,3,0,112,146,269,17,-1.000000,NaN
19,5,1,2,1,3,1,112,147,43,14,30.923546,NO.5?
20,5,1,2,1,3,2,165,147,39,16,44.539871,"55,57"
21,5,1,2,1,3,3,211,147,10,12,92.708313,&
22,5,1,2,1,3,4,229,147,19,15,83.305389,"59,"
23,5,1,2,1,3,5,260,147,43,13,92.713318,JALAN
24,5,1,2,1,3,6,311,146,42,13,92.713318,SAGU
25,5,1,2,1,3,7,364,146,17,16,64.547478,"18,"
26,4,1,2,1,4,0,196,170,99,14,-1.000000,NaN
27,5,1,2,1,4,1,196,170,51,14,92.773621,TAMAN
28,5,1,2,1,4,2,255,170,40,14,90.473213,DAYA
29,4,1,2,1,5,0,164,194,165,14,-1.000000,NaN
30,5,1,2,1,5,1,164,195,45,13,90.779556,81100
31,5,1,2,1,5,2,215,194,53,13,89.324615,JOHOR
32,5,1,2,1,5,3,276,194,53,14,50.003086,"BAHRU,"
33,4,1,2,1,6,0,219,217,52,14,-1.000000,NaN
34,5,1,2,1,6,1,219,217,52,14,80.620804,JOHOR.
35,2,1,3,0,0,0,93,274,305,48,-1.000000,NaN
36,3,1,3,1,0,0,93,274,305,48,-1.000000,NaN
37,4,1,3,1,1,0,93,274,305,48,-1.000000,NaN
38,5,1,3,1,1,1,93,275,55,47,9.897171,WAM
39,5,1,3,1,1,2,165,274,65,48,14.289932,MITT
40,5,1,3,1,1,3,254,274,66,47,0.000000,ANET
41,5,1,3,1,1,4,361,274,37,47,0.000000,t
42,2,1,4,0,0,0,52,343,226,14,-1.000000,NaN
43,3,1,4,1,0,0,52,343,226,14,-1.000000,NaN
44,4,1,4,1,1,0,52,343,226,14,-1.000000,NaN
45,5,1,4,1,1,1,52,344,76,13,93.995926,Document
46,5,1,4,1,1,2,136,344,18,13,58.195187,No
47,5,1,4,1,1,3,164,339,12,26,53.056396,:
48,5,1,4,1,1,4,186,343,92,13,40.491776,TDO1167104
49,2,1,5,0,0,0,323,571,26,11,-1.000000,NaN
50,3,1,5,1,0,0,323,571,26,11,-1.000000,NaN
51,4,1,5,1,1,0,323,571,26,11,-1.000000,NaN
52,5,1,5,1,1,1,323,571,26,11,95.000000,
53,2,1,6,0,0,0,30,373,413,315,-1.000000,NaN
54,3,1,6,1,0,0,30,373,413,315,-1.000000,NaN
55,4,1,6,1,1,0,52,373,290,16,-1.000000,NaN
56,5,1,6,1,1,1,52,375,33,13,96.157417,Date
57,5,1,6,1,1,2,165,373,85,16,95.575630,25/12/2018
58,5,1,6,1,1,3,257,373,57,14,43.471359,8:13:39
59,5,1,6,1,1,4,322,373,20,14,86.092651,PM
60,4,1,6,1,2,0,51,398,164,15,-1.000000,NaN
61,5,1,6,1,2,1,51,399,53,14,96.032394,Cashier
62,5,1,6,1,2,2,166,398,49,14,91.331627,MANIS
63,4,1,6,1,3,0,52,425,58,13,-1.000000,NaN
64,5,1,6,1,3,1,52,425,58,13,96.246758,Member
65,4,1,6,1,4,0,193,461,105,15,-1.000000,NaN
66,5,1,6,1,4,1,193,461,51,15,96.635826,CASH
67,5,1,6,1,4,2,254,461,44,15,95.638390,BILL
68,4,1,6,1,5,0,31,508,409,16,-1.000000,NaN
69,5,1,6,1,5,1,31,509,90,15,89.436523,CODE/DESC
70,5,1,6,1,5,2,202,508,44,13,76.540878,PRICE
71,5,1,6,1,5,3,258,500,10,30,48.958912,—
72,5,1,6,1,5,4,277,508,24,13,69.955391,Disc
73,5,1,6,1,5,5,376,508,64,12,20.896141,AMOUITE
74,4,1,6,1,6,0,72,532,371,18,-1.000000,NaN
75,5,1,6,1,6,1,72,533,30,17,63.109100,Quy
76,5,1,6,1,6,2,224,532,21,12,65.692856,RM
77,5,1,6,1,6,3,422,532,21,12,74.694725,RM
78,4,1,6,1,7,0,30,570,365,13,-1.000000,NaN
79,5,1,6,1,7,1,30,572,107,11,73.785477,9556939040118
80,5,1,6,1,7,2,162,572,11,11,48.406731,KF
81,5,1,6,1,7,3,184,570,91,12,89.827690,MODELLING
82,5,1,6,1,7,4,283,572,23,10,96.696236,CLAY
83,5,1,6,1,7,5,314,574,7,8,81.702812,KIDDY
84,5,1,6,1,7,6,352,571,43,11,85.545967,FISH
85,4,1,6,1,8,0,78,598,365,14,-1.000000,NaN
86,5,1,6,1,8,1,78,599,29,13,29.747314,1PC
87,5,1,6,1,8,2,140,601,4,5,32.296738,*
88,5,1,6,1,8,3,205,598,41,12,88.556862,9.00)
89,5,1,6,1,8,4,277,598,31,13,56.575371,"6,00"
90,5,1,6,1,8,5,412,599,31,11,71.230843,9.00
91,4,1,6,1,9,0,248,640,195,16,-1.000000,NaN
92,5,1,6,1,9,1,248,643,33,13,47.391022,Total
93,5,1,6,1,9,2,412,640,31,13,68.852562,"9,00"
94,4,1,6,1,10,0,120,671,323,17,-1.000000,NaN
95,5,1,6,1,10,1,120,672,32,13,93.197502,Rour
96,5,1,6,1,10,2,161,672,30,16,94.690315,ding
97,5,1,6,1,10,3,196,671,88,17,95.542847,Adjustment
98,5,1,6,1,10,4,412,671,31,13,92.525795,0.00
99,2,1,7,0,0,0,88,704,204,19,-1.000000,NaN
100,3,1,7,1,0,0,88,704,204,19,-1.000000,NaN
101,4,1,7,1,1,0,88,704,204,19,-1.000000,NaN
102,5,1,7,1,1,1,88,704,86,16,68.743958,Round::d
103,5,1,7,1,1,2,181,704,49,16,93.007645,Total
104,5,1,7,1,1,3,239,704,53,19,93.597260,(RM):
105,2,1,8,0,0,0,402,696,43,23,-1.000000,NaN
106,3,1,8,1,0,0,402,696,43,23,-1.000000,NaN
107,4,1,8,1,1,0,402,696,43,23,-1.000000,NaN
108,5,1,8,1,1,1,402,696,43,23,95.761620,9.60
109,2,1,9,0,0,0,206,748,63,37,-1.000000,NaN
110,3,1,9,1,0,0,206,748,63,37,-1.000000,NaN
111,4,1,9,1,1,0,206,748,35,13,-1.000000,NaN
112,5,1,9,1,1,1,206,748,35,13,95.114746,Cash
113,4,1,9,1,2,0,206,772,63,13,-1.000000,NaN
114,5,1,9,1,2,1,206,772,63,13,96.185242,CHANGE
115,2,1,10,0,0,0,307,731,142,130,-1.000000,NaN
116,3,1,10,1,0,0,307,731,142,130,-1.000000,NaN
117,4,1,10,1,1,0,307,731,142,130,-1.000000,NaN
118,5,1,10,1,1,1,307,731,142,130,95.000000,
119,2,1,11,0,0,0,98,845,251,33,-1.000000,NaN
120,3,1,11,1,0,0,98,845,251,33,-1.000000,NaN
121,4,1,11,1,1,0,98,845,251,13,-1.000000,NaN
122,5,1,11,1,1,1,98,846,54,12,90.619637,GOODS
123,5,1,11,1,1,2,160,846,37,12,90.347649,SOLD
124,5,1,11,1,1,3,205,846,25,11,95.883247,ARE
125,5,1,11,1,1,4,238,845,28,13,92.218117,NOT
126,5,1,11,1,1,5,275,846,74,12,65.754501,RETURNAP
127,4,1,11,1,2,0,192,865,116,13,-1.000000,NaN
128,5,1,11,1,2,1,192,865,116,13,96.140808,EXCHANGEABLE
129,2,1,12,0,0,0,309,887,30,36,-1.000000,NaN
130,3,1,12,1,0,0,309,887,30,36,-1.000000,NaN
131,4,1,12,1,1,0,309,887,30,36,-1.000000,NaN
132,5,1,12,1,1,1,309,887,30,36,95.000000,
133,2,1,13,0,0,0,165,944,163,32,-1.000000,NaN
134,3,1,13,1,0,0,165,944,163,32,-1.000000,NaN
135,4,1,13,1,1,0,204,944,88,13,-1.000000,NaN
136,5,1,13,1,1,1,204,944,51,13,96.105522,THANK
137,5,1,13,1,1,2,261,944,31,13,79.171539,YOU
138,4,1,13,1,2,0,165,963,163,13,-1.000000,NaN
139,5,1,13,1,2,1,165,963,53,13,96.238052,PLEASE
140,5,1,13,1,2,2,225,963,39,13,91.350891,COME
141,5,1,13,1,2,3,273,964,45,12,67.975662,AGATY
142,5,1,13,1,2,4,327,964,1,8,18.719498,t

Syntax: cv2.rectangle(image, start_point, end_point, color, thickness)  
Parameters:  
image: It is the image on which rectangle is to be drawn.  
start_point: It is the starting coordinates of rectangle. The coordinates are represented as tuples of two values i.e. (X coordinate value, Y coordinate value).  
end_point: It is the ending coordinates of rectangle. The coordinates are represented as tuples of two values i.e. (X coordinate value, Y coordinate value).  
color: It is the color of border line of rectangle to be drawn. For BGR, we pass a tuple. eg: (255, 0, 0) for blue color.  
thickness: It is the thickness of the rectangle border line in px. Thickness of -1 px will fill the rectangle shape by the specified color.  
Return Value: It returns an image.  
  
  
Syntax: cv2.putText(image, text, org, font, fontScale, color[, thickness[, lineType[, bottomLeftOrigin]]])  
Parameters:  
image: It is the image on which text is to be drawn.  
text: Text string to be drawn.  
org: It is the coordinates of the bottom-left corner of the text string in the image. The coordinates are represented as tuples of two values i.e. (X coordinate value, Y coordinate value).  
font: It denotes the font type. Some of font types are FONT_HERSHEY_SIMPLEX, FONT_HERSHEY_PLAIN, , etc.  
fontScale: Font scale factor that is multiplied by the font-specific base size.  
color: It is the color of text string to be drawn. For BGR, we pass a tuple. eg: (0, 0, 255) for red color.  
thickness: It is the thickness of the line in px.  
lineType: This is an optional parameter.It gives the type of the line to be used.  
bottomLeftOrigin: This is an optional parameter. When it is true, the image data origin is at the bottom-left corner. Otherwise, it is at the top-left corner.  
Return Value: It returns an image.  

The shape of an image is accessed by img.shape. It returns a tuple of the number of rows, columns, and channels (if the image is color):  
print( img.shape ) will return (342, 548, 3)

In [ ]:
# For graph modeling
xmin,ymin,xmax,ymax,Object = [],[],[],[],[]
df = pd.DataFrame() 

# Initialize a counter var for the 'text' detected in d for forloop use later
n_boxes = len(d['text'])

for i in range(n_boxes):
    if int(float(d['conf'][i])) >= 0.74:
        (x, y, w, h) = (d['left'][i], d['top'][i], d['width'][i], d['height'][i])
        text = d['text'][i]
      
        img = cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 1)
        img = cv2.putText(img, text, (x, y - 1), cv2.FONT_HERSHEY_DUPLEX, 0.6, (0, 0, 255), 1)

        img_height, img_width = img.shape[0], img.shape[1]
        
        xmin.append(x)
        ymin.append(y)
        xmax.append(x + w)
        ymax.append(y + h) 
        Object.append(text)

df['xmin'], df['ymin'], df['xmax'], df['ymax'], df['Object']  = xmin,ymin,xmax,ymax,Object 

# Remove empty object from df
df = df[df.Object != " "]

print(df)

df.to_csv('test550_scratchpart2' + '.csv' ,index = False)
cv2.imwrite('test550_scratchpart2' + '.jpg', img)

# Syntax: cv2.imwrite(filename, image) to save the image
cv2.imwrite(output, img)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

    xmin  ymin  xmax  ymax         Object
0     75    32   126    55            tan
1    138    37   229    55           woon
2    241    37   319    63           yann
3     73    97   125   110           BOOK
4    132    97   178   110            TAK
5    186    95   261   112         (TAMAN
6    269    95   327   112          DAYA)
7    338    96   370   109            SDN
8    380    96   419   109            BHD
9    112   147   155   161          NO.5?
10   165   147   204   163          55,57
11   211   147   221   159              &
12   229   147   248   162            59,
13   260   147   303   160          JALAN
14   311   146   353   159           SAGU
15   364   146   381   162            18,
16   196   170   247   184          TAMAN
17   255   170   295   184           DAYA
18   164   195   209   208          81100
19   215   194   268   207          JOHOR
20   276   194   329   208         BAHRU,
21   219   217   271   231         JOHOR.
22    93   275   148   322            WAM
23   165   274   230   322           MITT
24    52   344   128   357       Document
25   136   344   154   357             No
26   164   339   176   365              :
27   186   343   278   356     TDO1167104
29    52   375    85   388           Date
30   165   373   250   389     25/12/2018
31   257   373   314   387        8:13:39
32   322   373   342   387             PM
33    51   399   104   413        Cashier
34   166   398   215   412          MANIS
35    52   425   110   438         Member
36   193   461   244   476           CASH
37   254   461   298   476           BILL
38    31   509   121   524      CODE/DESC
39   202   508   246   521          PRICE
40   258   500   268   530              —
41   277   508   301   521           Disc
42   376   508   440   520        AMOUITE
43    72   533   102   550            Quy
44   224   532   245   544             RM
45   422   532   443   544             RM
46    30   572   137   583  9556939040118
47   162   572   173   583             KF
48   184   570   275   582      MODELLING
49   283   572   306   582           CLAY
50   314   574   321   582          KIDDY
51   352   571   395   582           FISH
52    78   599   107   612            1PC
53   140   601   144   606              *
54   205   598   246   610          9.00)
55   277   598   308   611           6,00
56   412   599   443   610           9.00
57   248   643   281   656          Total
58   412   640   443   653           9,00
59   120   672   152   685           Rour
60   161   672   191   688           ding
61   196   671   284   688     Adjustment
62   412   671   443   684           0.00
63    88   704   174   720       Round::d
64   181   704   230   720          Total
65   239   704   292   723          (RM):
66   402   696   445   719           9.60
67   206   748   241   761           Cash
68   206   772   269   785         CHANGE
69   307   731   449   861
70    98   846   152   858          GOODS
71   160   846   197   858           SOLD
72   205   846   230   857            ARE
73   238   845   266   858            NOT
74   275   846   349   858       RETURNAP
75   192   865   308   878   EXCHANGEABLE
77   204   944   255   957          THANK
78   261   944   292   957            YOU
79   165   963   218   976         PLEASE
80   225   963   264   976           COME
81   273   964   318   976          AGATY
82   327   964   328   972              t